# Generated by Django 3.1.5 on 2021-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notam_id', models.CharField(max_length=15)),
                ('airport', models.CharField(max_length=4)),
                ('qcode', models.CharField(max_length=4)),
                ('message', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=4)),
                ('designator', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=5)),
            ],
        ),
    ]
