# Generated by Django 3.1.5 on 2021-02-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_auto_20210205_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='notam',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
