# Generated by Django 3.1.5 on 2021-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_notam_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4)),
                ('purpose', models.CharField(max_length=4)),
            ],
        ),
    ]
