# Generated by Django 3.1.5 on 2021-02-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notam',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
