# Generated by Django 3.1.5 on 2021-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_auto_20210226_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notam',
            name='comment',
            field=models.CharField(default='', max_length=511),
        ),
    ]
